### ISSUE TITLE
onkyrimote doesn't start

### ISSUE THREAD

**Issue by szygmunt** [kmohrf/onkyrimote#1]
Hi,
i have problem with onkyrimote. I have this log after fire up onkyrimote:
`szym@pi:~ $ onkyrimote --help
Traceback (most recent call last):
  File "/usr/local/bin/onkyrimote", line 7, in <module>
    from onkyrimote.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/onkyrimote/__main__.py", line 3, in <module>
    from onkyrimote.device import SUPPORTED_DEVICES
  File "/usr/local/lib/python3.5/dist-packages/onkyrimote/device/__init__.py", line 35, in <module>
    importlib.import_module("." + module_name, package=__package__)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/dist-packages/onkyrimote/device/onkyo.py", line 43
    raise ValueError(f"Unsupported channel: {str(channel.value)}") from exc
                                                                ^
SyntaxError: invalid syntax`

pigpio is installed with apt.

**Comment by kmohrf** [comment]
Hey,

it seems like you’re using Python 3.5. Unfortunately you’ll need Python 3.7 (or maybe just maybe Python 3.6 is sufficient as well, none of my systems ever had Python 3.6 so it wasn’t a target) for onkyrimote to work. All current Linux distributions ship at least Python 3.7. Maybe you can solve the problem by upgrading your system to the latest version if that is an option for you.

**Comment by kmohrf** [comment]
Did this fix your problem @szygmunt?

**Comment by szygmunt** [comment]
Dnia 30 października 2020 14:29:41 CET, Konrad Mohrfeldt <notifications@github.com> napisał(a):
>Did this fix your problem @szygmunt?

Hi,

I have to upgrade (reinstall) raspbian on my uSD card because in Jessie python is only in 3.5 version. If i complete it i'll give you feedback
-- 
Szymon Zygmunt

**Comment by kmohrf** [comment]
Please reopen this if you encounter the same problem with Python 3.6+.
